//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_
    {
        public string TeacherEmail { get; set; }
        public string CompanyName { get; set; }
        public string ContractContent { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string InternLocation { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Teacher Teacher { get; set; }

        public Contract_() { }

        public Contract_(string teacherEmail, string companyName, string contractContent, DateTime startTime, DateTime endTime, string internLocation, Company company, Teacher teacher)
        {
            TeacherEmail = teacherEmail;
            CompanyName = companyName;
            ContractContent = contractContent;
            StartTime = startTime;
            EndTime = endTime;
            InternLocation = internLocation;
            Company = company;
            Teacher = teacher;
        }
    }
}
