//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string PhoneNumber { get; set; }
        public string StudentName { get; set; }
        public string ClassName { get; set; }
        public string CompanyName { get; set; }
        public string TeacherEmail { get; set; }
        public Nullable<int> CompanyMark { get; set; }
        public Nullable<int> TeacherMark { get; set; }
    
        public virtual Class_ Class_ { get; set; }
        public virtual Company Company { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
